# -*- coding: utf-8 -*-
"""LTX-2.3_T2V_I2V_A2V_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YootFpEIrSYMAwvTdJ0drIjKx6kw_uQb

# LTX-2.3 — Notebook chạy Text-to-Video / Image-to-Video / Audio-to-Video

Notebook này dùng repo **chính thức** của Lightricks: [github.com/Lightricks/LTX-2](https://github.com/Lightricks/LTX-2) (package `ltx-pipelines`), chạy trực tiếp bằng Python — không cần ComfyUI GUI.

**Yêu cầu:**
- GPU 24–54GB VRAM (Colab Pro/A100, Kaggle GPU, hoặc GPU thuê ngoài)
- ~60–80GB dung lượng ổ đĩa trống để tải model (checkpoint 22B ~44GB bf16 + Gemma 3 12B ~24GB + upscaler + LoRA)
- Tài khoản HuggingFace đã **Accept** điều khoản của model `google/gemma-3-12b-it-qat-q4_0-unquantized` (model gated)

**Lưu ý về VRAM 24–54GB:** notebook mặc định bật `fp8-cast` quantization — an toàn cho toàn dải VRAM này mà gần như không giảm chất lượng. Nếu bạn ở mức 40GB+ và muốn chất lượng tối đa, có thể tắt ở Step 4 (biến `USE_FP8 = False`).

**Nếu chạy trên Kaggle:** nhớ bật **Internet** trong Notebook Settings, và đổi các đường dẫn `/content/...` bên dưới thành `/kaggle/working/...`.

## Step 1: Environment Setup
"""

# Kiểm tra GPU và VRAM khả dụng
!nvidia-smi

import sys, torch
print("Python:", sys.version)
print("PyTorch CUDA available:", torch.cuda.is_available() if 'torch' in dir() else "torch chưa cài, sẽ cài ở Step 2")

# Biến môi trường tối ưu bộ nhớ CUDA (khuyến nghị chính thức từ LTX-2 khi dùng fp8-cast)
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# Nếu chạy trên Kaggle, đổi WORKDIR thành "/kaggle/working"
WORKDIR = "/content"
os.makedirs(WORKDIR, exist_ok=True)
os.chdir(WORKDIR)
print("Working dir:", os.getcwd())

"""## Step 2: Clone project & Install Dependencies"""

# Commented out IPython magic to ensure Python compatibility.
# Clone repo chính thức Lightricks/LTX-2
!git clone https://github.com/Lightricks/LTX-2.git
# %cd {WORKDIR}/LTX-2

# Cài đặt dependencies.
# Lưu ý: README chính thức khuyến nghị `uv sync --frozen`, nhưng lệnh đó tạo virtualenv riêng (.venv)
# không tự động áp dụng cho kernel notebook hiện tại. Trong môi trường Colab/Kaggle, cách đơn giản và
# đáng tin cậy hơn là cài trực tiếp vào kernel đang chạy bằng pip -e:

!pip install -e packages/ltx-core -q
!pip install -e packages/ltx-pipelines -q

# ffmpeg cần cho việc encode video output
!apt-get -qq update && apt-get -qq install -y ffmpeg > /dev/null

print("✅ Cài đặt xong.")

# (Tuỳ chọn) Xem toàn bộ tham số CLI thật của từng pipeline — hữu ích nếu bạn muốn
# tinh chỉnh sâu hơn những gì notebook này bao phủ (resolution, seed, negative prompt, v.v.)
!python -m ltx_pipelines.ti2vid_two_stages --help

"""## Step 3: Download All Required Models

Model `google/gemma-3-12b-it-qat-q4_0-unquantized` là **gated** — trước khi chạy cell tải bên dưới,
vào trang HuggingFace của model này và bấm **Agree and access repository**, sau đó đăng nhập bằng
Access Token (quyền Read, bật scope "read gated repos" nếu dùng fine-grained token).
"""

!pip install -U "huggingface_hub[cli]" -q
# HF_TOKEN_REMOVED
# Đăng nhập HuggingFace (sẽ hỏi paste Access Token)
!hf auth login

import os

MODELS_DIR = f"{WORKDIR}/LTX-2/models"
os.makedirs(f"{MODELS_DIR}/ltx-2.3", exist_ok=True)
os.makedirs(f"{MODELS_DIR}/gemma-3-12b", exist_ok=True)

# 1) Checkpoint chính (dev, bf16, 22B) — chất lượng cao nhất.
#    Kết hợp với fp8-cast quantization ở Step 4 để vừa VRAM 24-54GB.
!hf download Lightricks/LTX-2.3 ltx-2.3-22b-dev.safetensors --local-dir {MODELS_DIR}/ltx-2.3

# 2) Spatial upscaler — bắt buộc cho pipeline 2 giai đoạn (Stage 2 upsample 2x)
!hf download Lightricks/LTX-2.3 ltx-2.3-spatial-upscaler-x2-1.1.safetensors --local-dir {MODELS_DIR}/ltx-2.3

# 3) Distilled LoRA — bắt buộc cho pipeline 2 giai đoạn (dùng để refine ở Stage 2)
!hf download Lightricks/LTX-2.3 ltx-2.3-22b-distilled-lora-384-1.1.safetensors --local-dir {MODELS_DIR}/ltx-2.3

# 4) Gemma 3 12B — text encoder của LTX-2.3 (tải toàn bộ repo)
!hf download google/gemma-3-12b-it-qat-q4_0-unquantized --local-dir {MODELS_DIR}/gemma-3-12b

print("✅ Đã tải xong toàn bộ model.")

"""## Step 4: Write the Text-to-Video / Image-to-Video / Audio-to-Video Generation Script

- `generate_video(..., image_path=None)` → **Text-to-Video**
- `generate_video(..., image_path="anh.jpg")` → **Image-to-Video**
- `generate_audio_to_video(...)` → **Audio-to-Video** (video được sinh ra khớp với 1 file audio đầu vào)

"""

import torch
from ltx_core.components.guiders import MultiModalGuiderParams
from ltx_core.loader import LTXV_LORA_COMFY_RENAMING_MAP, LoraPathStrengthAndSDOps
from ltx_core.model.video_vae import TilingConfig, get_video_chunks_number
from ltx_core.quantization.fp8_cast import build_policy as build_fp8_cast_policy
from ltx_pipelines.ti2vid_two_stages import TI2VidTwoStagesPipeline
from ltx_pipelines.utils.args import ImageConditioningInput
from ltx_pipelines.utils.media_io import encode_video

# ---- Đường dẫn model (khớp với những gì đã tải ở Step 3) ----
CHECKPOINT_PATH = f"{MODELS_DIR}/ltx-2.3/ltx-2.3-22b-dev.safetensors"
DISTILLED_LORA_PATH = f"{MODELS_DIR}/ltx-2.3/ltx-2.3-22b-distilled-lora-384-1.1.safetensors"
SPATIAL_UPSAMPLER_PATH = f"{MODELS_DIR}/ltx-2.3/ltx-2.3-spatial-upscaler-x2-1.1.safetensors"
GEMMA_ROOT = f"{MODELS_DIR}/gemma-3-12b"

# ---- Cấu hình VRAM ----
# True  = bật fp8-cast, khuyến nghị mặc định cho toàn dải 24-54GB VRAM
# False = full bf16, chỉ dùng nếu bạn có ~54GB VRAM trở lên và muốn chất lượng tối đa tuyệt đối
USE_FP8 = True

distilled_lora = [
    LoraPathStrengthAndSDOps(DISTILLED_LORA_PATH, 0.6, LTXV_LORA_COMFY_RENAMING_MAP),
]

pipeline = TI2VidTwoStagesPipeline(
    checkpoint_path=CHECKPOINT_PATH,
    distilled_lora=distilled_lora,
    spatial_upsampler_path=SPATIAL_UPSAMPLER_PATH,
    gemma_root=GEMMA_ROOT,
    loras=[],
    quantization=build_fp8_cast_policy(CHECKPOINT_PATH) if USE_FP8 else None,
)

print("✅ Pipeline đã sẵn sàng (fp8-cast =", USE_FP8, ")")

# Tham số guidance mặc định — copy từ ví dụ chính thức của Lightricks, dùng làm điểm khởi đầu tốt.
# Nếu output bị "cháy"/quá gắt: giảm cfg_scale. Nếu bám prompt kém: tăng nhẹ cfg_scale.
video_guider_params = MultiModalGuiderParams(
    cfg_scale=3.0, stg_scale=1.0, rescale_scale=0.7, modality_scale=3.0, skip_step=0, stg_blocks=[29],
)
audio_guider_params = MultiModalGuiderParams(
    cfg_scale=7.0, stg_scale=1.0, rescale_scale=0.7, modality_scale=3.0, skip_step=0, stg_blocks=[29],
)


def generate_video(
    prompt,
    output_path="output.mp4",
    negative_prompt="worst quality, low quality, blurry, distorted",
    seed=42,
    height=512,
    width=768,
    num_frames=121,       # phải theo dạng 8k+1 (vd 97, 121, 161...)
    frame_rate=25.0,
    num_inference_steps=40,
    image_path=None,      # None = Text-to-Video | truyền path ảnh = Image-to-Video
):
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    images = []
    if image_path is not None:
        # (path, frame_idx, strength, crf) — frame_idx=0 nghĩa là ảnh làm khung hình đầu tiên
        images = [ImageConditioningInput(image_path, 0, 1.0, 33)]

    tiling_config = TilingConfig.default()
    video, audio = pipeline(
        prompt=prompt,
        negative_prompt=negative_prompt,
        seed=seed,
        height=height,
        width=width,
        num_frames=num_frames,
        frame_rate=frame_rate,
        num_inference_steps=num_inference_steps,
        video_guider_params=video_guider_params,
        audio_guider_params=audio_guider_params,
        images=images,
        tiling_config=tiling_config,
    )
    encode_video(
        video=video,
        fps=frame_rate,
        audio=audio,
        output_path=output_path,
        video_chunks_number=get_video_chunks_number(num_frames, tiling_config),
    )
    print(f"✅ Đã lưu video tại: {output_path}")
    return output_path

import subprocess

def generate_audio_to_video(
    prompt,
    audio_path,
    output_path="output_a2v.mp4",
    audio_start_time=0.0,
    audio_max_duration=5.0,
):
    """Audio-to-Video: sinh video khớp với 1 file audio có sẵn (dùng pipeline CLI chính thức
    ltx_pipelines.a2vid_two_stage). Chạy qua CLI thay vì Python API vì đây là cách được README
    xác nhận rõ ràng nhất cho pipeline này."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    cmd = [
        "python", "-m", "ltx_pipelines.a2vid_two_stage",
        "--checkpoint-path", CHECKPOINT_PATH,
        "--distilled-lora", DISTILLED_LORA_PATH, "0.6",
        "--spatial-upsampler-path", SPATIAL_UPSAMPLER_PATH,
        "--gemma-root", GEMMA_ROOT,
        "--prompt", prompt,
        "--audio-path", audio_path,
        "--audio-start-time", str(audio_start_time),
        "--audio-max-duration", str(audio_max_duration),
        "--output-path", output_path,
    ]
    if USE_FP8:
        cmd += ["--quantization", "fp8-cast"]

    print("Đang chạy:", " ".join(cmd))
    subprocess.run(cmd, check=True, cwd=f"{WORKDIR}/LTX-2")
    print(f"✅ Đã lưu video tại: {output_path}")
    return output_path

"""## Step 5: Launch! 🚀"""

# 5.1 — TEXT-TO-VIDEO
t2v_path = generate_video(
    prompt=(
        "A golden retriever running through a field of sunflowers at sunset, "
        "camera tracking alongside at a low angle, warm cinematic lighting, "
        "shallow depth of field"
    ),
    output_path=f"{WORKDIR}/outputs/t2v_demo.mp4",
    height=320,      # Chiều cao chia hết cho 64 (64 * 5)
    width=512,       # Chiều rộng chia hết cho 64 (64 * 8)
    num_frames=33,   # Giảm mạnh số frame xuống còn 33
    num_inference_steps=20, # Giảm số step xuống để sinh video nhanh hơn
)

from IPython.display import Video
Video(t2v_path, embed=True)

# 5.2 — IMAGE-TO-VIDEO
# Upload 1 ảnh vào notebook trước (kéo thả vào file browser bên trái, hoặc dùng
# `from google.colab import files; files.upload()` trên Colab), rồi sửa đường dẫn bên dưới.

INPUT_IMAGE = f"{WORKDIR}/my_input_image.jpg"  # <-- đổi đường dẫn ảnh của bạn

i2v_path = generate_video(
    prompt="The person in the photo turns their head and smiles warmly, gentle wind moving their hair",
    image_path=INPUT_IMAGE,
    output_path=f"{WORKDIR}/outputs/i2v_demo.mp4",
    height=512,
    width=768,
    num_frames=121,
    num_inference_steps=40,
)

Video(i2v_path, embed=True)

# 5.3 — AUDIO-TO-VIDEO
# Upload 1 file audio (wav/mp3) vào notebook trước, rồi sửa đường dẫn bên dưới.

INPUT_AUDIO = f"{WORKDIR}/my_input_audio.wav"  # <-- đổi đường dẫn audio của bạn

a2v_path = generate_audio_to_video(
    prompt="A singer performing on stage with dynamic colored lights matching the beat",
    audio_path=INPUT_AUDIO,
    output_path=f"{WORKDIR}/outputs/a2v_demo.mp4",
    audio_max_duration=5.0,
)

Video(a2v_path, embed=True)